import ElementPlus, { ElMessage } from "element-plus";
import "element-plus/dist/index.css";
import { createApp } from "vue";
import App from "./App.vue";
import i18n from "./language/i18n";
import router from "./router";
const app = createApp(App);
app.config.globalProperties.$message = ElMessage;
app.use(router);
app.use(ElementPlus);
app.use(i18n);
app.mount("#app");
